### ISSUE TITLE
No module named 'sbg'

### ISSUE THREAD

**Issue by chanansh** [jdmaturen/shifted_beta_geometric_py#3]
After installing
`pip install git+https://github.com/jdmaturen/shifted_beta_geometric_py`

>  python -c "from shifted_beta_geometric import fit"
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/Users/x/anaconda3/lib/python3.6/site-packages/shifted_beta_geometric/__init__.py", line 1, in <module>
>     from sbg import derl
> ModuleNotFoundError: No module named 'sbg'

probably because of explicitly import from sbg within __init__ in sgb folder.

**Comment by chanansh** [comment]
suggest solution in PR #4
